language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - conda install --yes --quiet python=$TRAVIS_PYTHON_VERSION atlas numpy nose pip coverage pep8
  - pip install -q --no-deps git+git://github.com/Theano/Theano.git
  - pip install -q coveralls
# command to run tests
script:
  - pep8 blocks
  - nosetests --with-coverage --cover-package=blocks --with-doctest --doctest-options=+IGNORE_EXCEPTION_DETAIL
after_script:
  - coveralls
