sudo: false
cache:
  directories:
    - $TRAVIS_BUILD_DIR/mnist
branches:
  only:
    - master
language: python
python:
  - "2.7"
  - "3.4"
env:
  - TESTS=float32
  - TESTS=float64
before_install:
  - # Setup Python environment with BLAS libraries
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update -q --yes conda
  - |
      # Download MNIST for tests if not loaded from cache
      if find mnist -empty | read; then
        mkdir mnist
        cd mnist
        curl -O http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz \
             -O http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz \
             -O http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz \
             -O http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
        gunzip *-ubyte.gz
        cd -
      fi
  - export FUEL_DATA_PATH=$PWD
install:
  # Install all Python dependencies
  - conda install -q --yes python=$TRAVIS_PYTHON_VERSION mkl --file req-travis-conda.txt
  - pip install -q -r req-travis-pip.txt
script:
  - pip install . -r requirements.txt # Tests setup.py
  - # Must export environment variable so that the subprocess is aware of it
  - export THEANO_FLAGS=floatX=$TESTS,optimizer=fast_compile
  - export FUEL_FLOATX=$TESTS
  - export BLOCKS_PROFILE=true
  - # Running nose2 within coverage makes imports count towards coverage
  - bokeh-server &> /dev/null &
  - coverage run -p --source=blocks -m nose2.__main__ -v doctests
  - coverage run -p --source=blocks -m nose2.__main__ -v tests
after_script:
  - coverage combine
  - coveralls
